# This is a basic workflow to help you get started with Actions

name: Trigger

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env: 
      var1: "${{ github.ref == 'refs/head/main' && 'main' || github.ref == 'refs/head/test' && 'test' || null }}"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --data '{"ref": "main", "inputs": { "var1": "${{ env.var1 }}", "var2": "variable2" }}' \
          https://api.github.com/repos/MarcoRezkallah/try-workflow-dispatch/actions/workflows/blank.yml/dispatches


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
